# Análise Exploratória: Dados Bancários
O objetivo deste notebook é entender a estrutura do arquivo `dados_bancarios.csv` bruto, identificar valores nulos, inconsistências e definir quais regras de limpeza serão aplicadas no nosso script de transformação (ETL).

In [1]:
import pandas as pd

# Carregando os dados brutos
df = pd.read_csv("../data/raw/dados_bancarios.csv")
df.head()

              Nome       Conta               Cartão
0    Paulo Cardoso  9916311491  2790-2937-3674-5198
1   Felipe Martins  1939313049  9945-3692-5373-4194
2     Tiago Farias  1201414221  1726-8385-5167-6205
3    Mariana Nunes  3317321438  5334-0166-1358-0169
4  Nicolas Freitas   159276894  2893-1093-2465-0736

In [2]:
# Verificando os tipos de dados e valores nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    100 non-null    object
 1   Conta   100 non-null    int64
 2   Cartão  100 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [3]:
# Verificando estatísticas básicas (ex: tem transação com valor negativo onde não deveria?)
df.describe()

              Conta
count  1.000000e+02
mean   4.705395e+09
std    3.016714e+09
min    9.360597e+07
25%    1.982418e+09
50%    4.668448e+09
75%    7.327734e+09
max    9.959650e+09

### 📝 Conclusões para o pipeline (O que faremos no `transform.py`):
1. A coluna de `data` está como texto (string), precisaremos converter para formato `datetime`.
2. Encontramos valores nulos na coluna `status`, vamos preencher com 'DESCONHECIDO'.
3. Precisamos padronizar a coluna `tipo_transacao` para letras maiúsculas.